### ISSUE TITLE
Stremio Android tv 1.5.7 missing streams

### ISSUE THREAD

**Issue by Gurinkajidan** [anime-src/hanime-stremio#3]
This is the xiamo Mi stick 4K model miTV-AYFR0
I am using the official Stremio webpage and play store apk 1.5.7 Arm.  for android tvs and most of the streams arent found here for hanime.tv. after some research i installed the 1.5.8 apk for android mobiles and it works well on that matter, but since is for mobiles the interface is diffficult to use and doesnt call the subscription channels properly.
So we need help fixing this issue so it finds stream#s also on version 1.5.7 android tv apks please. Ty very much for the amazing app

**Comment by anime-src** [comment]
Try with latest, @dexter21767 made a fix
