### ISSUE TITLE
Stremio Google TV No Streams

### ISSUE THREAD

**Issue by Fstsoto** [anime-src/hanime-stremio#4]
It seems like no streams can be found on chromecast Google TV but works fine on Desktop. But i would really like to use it on my Google TV

**Comment by bilalinamdar** [comment]
I also want to confirm this doesn't work on firestick + stremio latest version as of now. same message as above. It works on pc only.

**Comment by anime-src** [comment]
Try with latest, @dexter21767 made a fix
