### ISSUE TITLE
Doesn't seem to work on Stremio-Web

### ISSUE THREAD

**Issue by GunGunGun** [anime-src/hanime-stremio#5]
URL: https://web.strem.io/#/detail/movie/kuroinu-1

Works fine one Stremio Desktop and http://127.0.0.1:11470/
Somehow, but Stremio-Web is very good and lightweight, it also looks better and probably the future of stremio, we should consider supporting it!

![image](https://github.com/anime-src/hanime-stremio/assets/6913739/b1cab95e-878e-48c7-bcb2-6fa7574bc691)

**Comment by anime-src** [comment]
Try with latest, @dexter21767 made a fix
