### ISSUE TITLE
Nvidia shield tv hanime.tv

### ISSUE THREAD

**Issue by Stofcri** [anime-src/hanime-stremio#8]
Links are not showing for hanime.tv on nvidia shield tv

**Comment by anime-src** [comment]
yes, manage to test in on Chromecast, i could say it's bug in stremio sdk, but it should work now

https://86f0740f37f6-hanime-stremio.baby-beamup.club/manifest.json

**Comment by Stofcri** [comment]
Hi,

Thank you for the follow up.
I can confirm it works well now.
Only difference is:
Looks like its no longer in adult section but in movies otherwise works
well on nvidia shield.

Thanks.
